management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    defaults:
      enabled: true