management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: full # 상세
      #mode: simple # 간략
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    defaults:
      enabled: true

# info 로 시작하면 info endpoint env 에  추가됨
info:
  name: developer
  age: 11